version: "3.7"
services: 
  web:
    build: web
    restart: always
    ports:
      - 5000:5000
    environment:
      - DEBUG=0
    networks:
      - flask_network

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network

  db:
    image: postgres
    stdin_open: true
    tty: true
    ports:
      - 5432:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DB=enquete
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/:/root/db/


networks:
  flask_network:

volumes:
  postgres_data:
